name       : haskell-unexceptionalio
version    : 0.4.0
release    : 3
source     :
    - https://hackage.haskell.org/package/unexceptionalio-0.4.0/unexceptionalio-0.4.0.tar.gz : 1785df9b14b064c37d33d7410d200797bfc81bb1400c2e68b1f65071c8b4fe25
license    : MIT
component  : programming.haskell
summary    : When you've caught all the exceptions that can be handled safely, this
    is what you're left with.
description: |
    When you've caught all the exceptions that can be handled safely, this is what you're left with.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
