name       : haskell-unexceptionalio
version    : 0.5.0
release    : 4
source     :
    - https://hackage.haskell.org/package/unexceptionalio-0.5.0/unexceptionalio-0.5.0.tar.gz : 2976612883668f3ea620771db4489b247002130672545434365ab172c0ae5912
license    : MIT
component  : programming.haskell
summary    : When you've caught all the exceptions that can be handled safely, this is what you're left with.
description: |
    When you've caught all the exceptions that can be handled safely, this is what you're left with.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
