name       : haskell-unexceptionalio
version    : 0.3.0
release    : 1
source     :
    - http://hackage.haskell.org/package/unexceptionalio-0.3.0/unexceptionalio-0.3.0.tar.gz : 927e2be6bb9ced73c1c17d79c981cadef4039d9ee45d2d3d6b4c133ff93ff0b8
license    : MIT
component  : programming.haskell
summary    : When you've caught all the exceptions that can be handled safely, this is what you're left with.
description: |
    When you've caught all the exceptions that can be handled safely, this is what you're left with.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register